# Generated by Django 5.2.6 on 2025-10-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='team_user',
        ),
    ]
