# Generated by Django 5.2.6 on 2025-10-05 16:11

import team.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', team.manager.UserManager()),
            ],
        ),
    ]
